# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/itsrxmmy/posh/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/itsrxmmy/posh

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/itsrxmmy/posh/CMakeFiles /home/itsrxmmy/posh//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/itsrxmmy/posh/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named posh

# Build rule for target.
posh: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 posh
.PHONY : posh

# fast build rule for target.
posh/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/posh.dir/build.make CMakeFiles/posh.dir/build
.PHONY : posh/fast

posh.o: posh.cc.o
.PHONY : posh.o

# target to build an object file
posh.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/posh.dir/build.make CMakeFiles/posh.dir/posh.cc.o
.PHONY : posh.cc.o

posh.i: posh.cc.i
.PHONY : posh.i

# target to preprocess a source file
posh.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/posh.dir/build.make CMakeFiles/posh.dir/posh.cc.i
.PHONY : posh.cc.i

posh.s: posh.cc.s
.PHONY : posh.s

# target to generate assembly for a file
posh.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/posh.dir/build.make CMakeFiles/posh.dir/posh.cc.s
.PHONY : posh.cc.s

posh/command_engine.o: posh/command_engine.cc.o
.PHONY : posh/command_engine.o

# target to build an object file
posh/command_engine.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/posh.dir/build.make CMakeFiles/posh.dir/posh/command_engine.cc.o
.PHONY : posh/command_engine.cc.o

posh/command_engine.i: posh/command_engine.cc.i
.PHONY : posh/command_engine.i

# target to preprocess a source file
posh/command_engine.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/posh.dir/build.make CMakeFiles/posh.dir/posh/command_engine.cc.i
.PHONY : posh/command_engine.cc.i

posh/command_engine.s: posh/command_engine.cc.s
.PHONY : posh/command_engine.s

# target to generate assembly for a file
posh/command_engine.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/posh.dir/build.make CMakeFiles/posh.dir/posh/command_engine.cc.s
.PHONY : posh/command_engine.cc.s

posh/errors.o: posh/errors.cc.o
.PHONY : posh/errors.o

# target to build an object file
posh/errors.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/posh.dir/build.make CMakeFiles/posh.dir/posh/errors.cc.o
.PHONY : posh/errors.cc.o

posh/errors.i: posh/errors.cc.i
.PHONY : posh/errors.i

# target to preprocess a source file
posh/errors.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/posh.dir/build.make CMakeFiles/posh.dir/posh/errors.cc.i
.PHONY : posh/errors.cc.i

posh/errors.s: posh/errors.cc.s
.PHONY : posh/errors.s

# target to generate assembly for a file
posh/errors.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/posh.dir/build.make CMakeFiles/posh.dir/posh/errors.cc.s
.PHONY : posh/errors.cc.s

posh/file_helper.o: posh/file_helper.cc.o
.PHONY : posh/file_helper.o

# target to build an object file
posh/file_helper.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/posh.dir/build.make CMakeFiles/posh.dir/posh/file_helper.cc.o
.PHONY : posh/file_helper.cc.o

posh/file_helper.i: posh/file_helper.cc.i
.PHONY : posh/file_helper.i

# target to preprocess a source file
posh/file_helper.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/posh.dir/build.make CMakeFiles/posh.dir/posh/file_helper.cc.i
.PHONY : posh/file_helper.cc.i

posh/file_helper.s: posh/file_helper.cc.s
.PHONY : posh/file_helper.s

# target to generate assembly for a file
posh/file_helper.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/posh.dir/build.make CMakeFiles/posh.dir/posh/file_helper.cc.s
.PHONY : posh/file_helper.cc.s

posh/ios/istream.o: posh/ios/istream.cc.o
.PHONY : posh/ios/istream.o

# target to build an object file
posh/ios/istream.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/posh.dir/build.make CMakeFiles/posh.dir/posh/ios/istream.cc.o
.PHONY : posh/ios/istream.cc.o

posh/ios/istream.i: posh/ios/istream.cc.i
.PHONY : posh/ios/istream.i

# target to preprocess a source file
posh/ios/istream.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/posh.dir/build.make CMakeFiles/posh.dir/posh/ios/istream.cc.i
.PHONY : posh/ios/istream.cc.i

posh/ios/istream.s: posh/ios/istream.cc.s
.PHONY : posh/ios/istream.s

# target to generate assembly for a file
posh/ios/istream.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/posh.dir/build.make CMakeFiles/posh.dir/posh/ios/istream.cc.s
.PHONY : posh/ios/istream.cc.s

posh/ios/ostream.o: posh/ios/ostream.cc.o
.PHONY : posh/ios/ostream.o

# target to build an object file
posh/ios/ostream.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/posh.dir/build.make CMakeFiles/posh.dir/posh/ios/ostream.cc.o
.PHONY : posh/ios/ostream.cc.o

posh/ios/ostream.i: posh/ios/ostream.cc.i
.PHONY : posh/ios/ostream.i

# target to preprocess a source file
posh/ios/ostream.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/posh.dir/build.make CMakeFiles/posh.dir/posh/ios/ostream.cc.i
.PHONY : posh/ios/ostream.cc.i

posh/ios/ostream.s: posh/ios/ostream.cc.s
.PHONY : posh/ios/ostream.s

# target to generate assembly for a file
posh/ios/ostream.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/posh.dir/build.make CMakeFiles/posh.dir/posh/ios/ostream.cc.s
.PHONY : posh/ios/ostream.cc.s

posh/utils.o: posh/utils.cc.o
.PHONY : posh/utils.o

# target to build an object file
posh/utils.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/posh.dir/build.make CMakeFiles/posh.dir/posh/utils.cc.o
.PHONY : posh/utils.cc.o

posh/utils.i: posh/utils.cc.i
.PHONY : posh/utils.i

# target to preprocess a source file
posh/utils.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/posh.dir/build.make CMakeFiles/posh.dir/posh/utils.cc.i
.PHONY : posh/utils.cc.i

posh/utils.s: posh/utils.cc.s
.PHONY : posh/utils.s

# target to generate assembly for a file
posh/utils.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/posh.dir/build.make CMakeFiles/posh.dir/posh/utils.cc.s
.PHONY : posh/utils.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... posh"
	@echo "... posh.o"
	@echo "... posh.i"
	@echo "... posh.s"
	@echo "... posh/command_engine.o"
	@echo "... posh/command_engine.i"
	@echo "... posh/command_engine.s"
	@echo "... posh/errors.o"
	@echo "... posh/errors.i"
	@echo "... posh/errors.s"
	@echo "... posh/file_helper.o"
	@echo "... posh/file_helper.i"
	@echo "... posh/file_helper.s"
	@echo "... posh/ios/istream.o"
	@echo "... posh/ios/istream.i"
	@echo "... posh/ios/istream.s"
	@echo "... posh/ios/ostream.o"
	@echo "... posh/ios/ostream.i"
	@echo "... posh/ios/ostream.s"
	@echo "... posh/utils.o"
	@echo "... posh/utils.i"
	@echo "... posh/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

