# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

ifneq ($(VERBOSE),1)
VV=@
endif

CU=/usr/bin/clang
MXX=/usr/bin/gcc
RC=/home/itsrxmmy/.cargo/bin/rustc
CC=/usr/bin/gcc
MM=/usr/bin/gcc
GC=/usr/bin/go
AS=/usr/bin/gcc
ZC=/usr/bin/zig
CXX=/usr/bin/gcc

SH=/usr/bin/g++
ZCSH=/usr/bin/zig
RCSH=/home/itsrxmmy/.cargo/bin/rustc
LD=/usr/bin/g++
GCLD=/usr/bin/go
ZCLD=/usr/bin/zig
RCLD=/home/itsrxmmy/.cargo/bin/rustc
AR=/usr/bin/ar
GCAR=/usr/bin/go
ZCAR=/usr/bin/zig
RCAR=/home/itsrxmmy/.cargo/bin/rustc

posh_LD=/usr/bin/g++
posh_CXX=/usr/bin/gcc
posh_CXX=/usr/bin/gcc

posh_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++23 -DNDEBUG
posh_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++23 -DNDEBUG
posh_LDFLAGS=-m64 -s

default:  posh

all:  posh

.PHONY: default all  posh

posh: build/linux/x86_64/release/posh
build/linux/x86_64/release/posh: build/.objs/posh/linux/x86_64/release/src/main.cc.o
	@echo linking.release posh
	@mkdir -p build/linux/x86_64/release
	$(VV)$(posh_LD) -o build/linux/x86_64/release/posh build/.objs/posh/linux/x86_64/release/src/main.cc.o $(posh_LDFLAGS)

build/.objs/posh/linux/x86_64/release/src/main.cc.o: src/main.cc
	@echo compiling.release src/main.cc
	@mkdir -p build/.objs/posh/linux/x86_64/release/src
	$(VV)$(posh_CXX) -c $(posh_CXXFLAGS) -o build/.objs/posh/linux/x86_64/release/src/main.cc.o src/main.cc

clean:  clean_posh

clean_posh: 
	@rm -rf build/linux/x86_64/release/posh
	@rm -rf build/linux/x86_64/release/posh.sym
	@rm -rf build/.objs/posh/linux/x86_64/release/src/main.cc.o

